### ISSUE TITLE
MobileDoc deprecation

### ISSUE THREAD

**Issue by v411e** [silverbulletmd/silverbullet-ghost#6]
Ghost is switching from MobileDoc to Lexical: https://ghost.org/docs/changes/

> **note**
> To remain compatible with Ghost, integrations that rely on Mobiledoc should switch to using Lexical.

Does it make sense to switch to the official JavaScript Client Library? https://ghost.org/docs/admin-api/javascript/

**Comment by zefhemel** [comment]
Hmm, alright. Yes I suppose we have to make this move. I'm trying to recall why I'm not using the official Ghost API, perhaps I couldn't get it to work with Deno. I'd have to check again if that works now.

**Comment by AudunVN** [comment]
The plug no longer relies on MobileDoc as of commit https://github.com/silverbulletmd/silverbullet-ghost/commit/dcc84320eb49c70923109c44a3baaeda37633bf4 - should this issue be closed, and perhaps a new issue opened regarding switching to the official Ghost Admin API JS client?

**Comment by zefhemel** [comment]
Yes I fixed this a while ago. You can create a separate issue, but from the top of my head I think the official SDK didn't work very well with Deno and/or SB. Don't remember the issue, maybe it uses node.js crypto apis.

**Comment by v411e** [comment]
Yes, I once tried the official SDK with deno and could not get it to work. Thank you for fixing this plug
